config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "plants#index"

  resources :plants do
    resources :waterings
  end

  delete "images/:id/purge", to: "images#purge", as: "purge_image"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plant.rb
class Plant < ApplicationRecord
    validates :name, presence: true
    validates :birthday, presence: true

    has_many_attached :images
    has_many :waterings, dependent: :destroy

    def age
        days_parser(birthday).to_i
    end

    def birth
        self.birthday.strftime("%Y/%m/%d")
    end

    def images=(attachables)
        attachables = Array(attachables).compact_blank

       if attachables.any?
         attachment_changes["images"] =
           ActiveStorage::Attached::Changes::CreateMany.new("images", self, images.blobs + attachables)
       end
    end

    private
    def days_parser(date)
        DateTime.now - DateTime.parse("#{date}")
    end
end

app/models/watering.rb
class Watering < ApplicationRecord
  belongs_to :plant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def purge
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge
    redirect_back fallback_location: root_path
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @plants = Plant.all
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)

    
    if @plant.save
      redirect_to @plant
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])

    if @plant.update(plant_params)
      redirect_to @plant
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def plant_params
      params.require(:plant).permit(:name, :description, :birthday, :last_watering, images: [])
    end
end

app/controllers/waterings_controller.rb
class WateringsController < ApplicationController
    def create
      @plant = Plant.find(params[:plant_id])
      @watering = @plant.waterings.create
      redirect_to plant_path(@plant)
    end

    # private
    #   def watering_params
    #     params.require(:watering).permit(:last_watering)
    #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/waterings_helper.rb
module WateringsHelper
end

app/views/images/_delete_images.html.erb
<% plant.images.each do |image| %>
  <div class="flex-container">
    <div>
      <% if image.representable? %>
          <%= image_tag image.representation(resize_to_limit: [300, 300]) %>
      <% end %>
    </div>
    
    <button>
      <%= link_to "Delete this image", purge_image_path(image), data: {
                              turbo_method: :delete,
                              turbo_confirm: "Are you sure to delete this image?"
                          } %>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/_error_display.html.erb
<% plant.errors.full_messages.each do |message| %>
    <div><%= message %></div>
<% end %>

app/views/plants/_form.html.erb
<%= form_with model: plant do |form| %>
  <div class="plant-edit">
    <div>
      <%= form.label :images, "Select or Upload Images", class: "upload-button" %>
      <%= form.file_field :images, direct_upload: true, multiple: true, capture: "user", accept: "image/*" %>
    </div>

    <div>
      <%= form.label :name %>
    </div>
    <div>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :description %>
    </div>
    <div>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :birthday %>
    </div>
    <div>
      <%= form.date_field :birthday %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/plants/edit.html.erb
<div class="flex-container">
  <div class="grid-container">
    <div class="plant">
      <h1>Edit a plant in your collection!</h1>

      <%= render "error_display", plant: @plant %>

      <%= render "images/delete_images", plant: @plant%>

      <%= render "form", plant: @plant %>
    </div>
    <div class="plant-navigation">
      <div><%= link_to "Go back", plant_path %></div>
    </div>
  </div>
</div>

app/views/plants/index.html.erb
<div class="flex-container">
  <h1>Your Plants</h1>

  <div class="grid-container">
    <% @plants.each do |plant| %>
      <div class="plant">
        <h2><%= plant.name %></h2>
        <div class="plant-images" data-controller="slideshow" data-slideshow-index-value="0">
          <button data-action="slideshow#previous"> ← </button>
          <% if plant.images.attached? %>
            <% plant.images.each do |image| %>
              <div data-slideshow-target="slide">
                <% if image.representable? %>
                  <%= link_to plant do %>
                    <%= image_tag image.representation(resize_to_limit: [250, 250]) %>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <button data-action="slideshow#next"> → </button>
        </div>

        <div class="plant-info">
          <p> <%= plant.name %> started growing on <%= plant.birth %>.</p>
          <p>
            <% if plant.waterings.any? %>
              It was last watered <%= time_ago_in_words(plant.waterings.last.created_at) %> ago.
            <% end %>
          </p>
          <p> Check out more here: <%= link_to plant.name, plant %></p>
        </div>
      </div>
    <% end %>
    <div class="plant-navigation">
      <div><%= link_to "New Plant", new_plant_path %></div>
    </div>
  </div>
</div>

app/views/plants/new.html.erb
<div class="flex-container">
  <div class="grid-container">
    <div class="plant">
      <h1>Add a new plant to your home!</h1>

      <%= render "error_display", plant: @plant %>

      <%= render "form", plant: @plant %>

    </div>
    <div class="plant-navigation">
      <div><%= link_to "Go back", root_path %></div>
  </div>
</div>

app/views/plants/show.html.erb
<div class="flex-container">
  <div class="grid-container">
    <div class="plant">
      <h1><%= @plant.name %></h1>
      <div class="plant-images" data-controller="slideshow" data-slideshow-index-value="0">
        <button data-action="slideshow#previous"> ← </button>
        <% @plant.images.each do |image| %>
          <div data-slideshow-target="slide">
            <% if image.representable? %>
              <%= image_tag image.representation(resize_to_limit: [300, 300]) %>
            <% end %>
          </div>
        <% end %>
        <button data-action="slideshow#next"> → </button>
      </div>

      <div class="plant-info">
        <p> <%= @plant.name %> started growing on <%= @plant.birth %>.</p>
        <% if @plant.waterings.any? %>
          <p> It was last watered <%= time_ago_in_words(@plant.waterings.last.created_at) %> ago. </p>
        <% elsif %>
          <p> This plants has not been watered yet! </p>
        <% end %>
        <p> <%= @plant.description %> </p>

        <%= form_with model: [ @plant, @plant.waterings.build ] do |form| %>
        <div>
          <%= form.submit "Water this plant!" %>
        </div>
        <% end %>
    </div>
  </div>
  <div class="plant-navigation">
    <div><%= link_to "Go back", root_path %></div>
    <div><%= link_to "Edit Plant", edit_plant_path(@plant) %></div>
    <div><%= link_to "Destroy", plant_path(@plant), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure to delete #{@plant.name}?"
                      } %>
    </div>
  </div>
</div>